[package]
name = "async-winit"
version = "0.1.0"
edition = "2021"
authors = ["John Nunley <jtnunley01@gmail.com>"]
description = "Use winit like an async runtime"
repository = "https://github.com/notgull/async-winit"
license = "MIT OR Apache-2.0"

[dependencies]
async-broadcast = "0.5.1"
async-channel = "1.8.0"
concurrent-queue = "2.2.0"
futures-lite = "1.13.0"
once_cell = "1.17.1"
raw-window-handle = "0.5.2"
winit = { version = "0.28.3", default-features = false }

[dev-dependencies]
winit = { version = "0.28.3", default-features = false, features = ["x11"] }
